<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [correction suite]">
  <test thread-count="5" name="correction test(failed)">
    <groups>
      <run>
        <include name="calculette"/>
        <include name="spring"/>
        <exclude name="lancer"/>
      </run>
    </groups>
    <classes>
      <class name="bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest">
        <methods>
          <include name="springTestContextBeforeTestClass"/>
          <include name="operationTest"/>
          <include name="multiplicationTest"/>
          <include name="springTestContextPrepareTestInstance"/>
          <include name="springTestContextAfterTestClass"/>
          <include name="springTestContextBeforeTestMethod"/>
          <include name="additionTest"/>
          <include name="divisionTest" invocation-numbers="0 1 2 3"/>
          <include name="divisionTestException"/>
          <include name="springTestContextAfterTestMethod"/>
          <include name="soustractionTest"/>
        </methods>
      </class> <!-- bstorm.akimt.demoTestNG.correction.calculette.CalculetteTest -->
    </classes>
  </test> <!-- correction test(failed) -->
</suite> <!-- Failed suite [correction suite] -->
